#requires -Version 7.0

<#
.SYNOPSIS
    <Short description of what the script does.>

.DESCRIPTION
    <Detailed description of the purpose of the script.>

    Describe:
    - What the script does
    - What it does NOT do
    - Required permissions
    - Required PowerShell modules
    - Supported operating systems / services
    - Possible impact on the target environment

    SECURITY:
    Do not place passwords, API keys, access tokens, private keys,
    customer names, tenant IDs or other confidential information
    directly in this script.

.PARAMETER Target
    <Describe the target computer, user, service or resource.>

.PARAMETER LogPath
    Optional path for the script log file.
    The default is a Logs folder below the script directory.

.PARAMETER Force
    <Describe exactly what Force changes or bypasses. Remove this
    parameter if it is not required.>

.EXAMPLE
    .\PowerShell-Script-Template.ps1 -Target 'Server01' -WhatIf

    Shows what the script would change without applying the modifying action.

.EXAMPLE
    .\PowerShell-Script-Template.ps1 -Target 'Server01' -Verbose

    Runs the script and displays verbose information.

.EXAMPLE
    .\PowerShell-Script-Template.ps1 -Target 'Server01' -LogPath 'C:\Logs\MyScript.log'

    Runs the script and writes log entries to the specified file.

.INPUTS
    None.
    <Replace this section if the script accepts pipeline input.>

.OUTPUTS
    <Describe objects or files returned/generated by the script.>

.NOTES
    Author      : Hubert Inderwildi
    Repository  : PowerShell-Scripts-and-Tips
    Version     : 1.0.0
    PowerShell  : 7.x
    Created     : <YYYY-MM-DD>
    Updated     : <YYYY-MM-DD>

    Before publishing:
    - Remove customer-specific information.
    - Remove passwords, secrets, tokens and private keys.
    - Replace internal domains, server names, IP addresses and e-mail addresses.
    - Test in a non-production environment.
    - Run PSScriptAnalyzer where possible.
    - Test modifying operations with -WhatIf.

.LINK
    https://github.com/chwildi/PowerShell-Scripts-and-Tips
#>

[CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'Medium')]
param(
    [Parameter(Mandatory = $true, Position = 0)]
    [ValidateNotNullOrEmpty()]
    [string]$Target,

    [Parameter(Mandatory = $false)]
    [ValidateNotNullOrEmpty()]
    [string]$LogPath = (Join-Path -Path $PSScriptRoot -ChildPath "Logs\$((Get-Date).ToString('yyyyMMdd-HHmmss'))-Script.log"),

    [Parameter(Mandatory = $false)]
    [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Write-Log {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]
        [string]$Message,

        [Parameter(Mandatory = $false)]
        [ValidateSet('INFO', 'OK', 'WARN', 'ERROR')]
        [string]$Level = 'INFO'
    )

    $timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    $entry = "[$timestamp] [$Level] $Message"

    switch ($Level) {
        'ERROR' { Write-Error $Message }
        'WARN'  { Write-Warning $Message }
        default { Write-Verbose $entry }
    }

    try {
        $logDirectory = Split-Path -Path $LogPath -Parent
        if ($logDirectory -and -not (Test-Path -LiteralPath $logDirectory)) {
            New-Item -ItemType Directory -Path $logDirectory -Force | Out-Null
        }

        Add-Content -LiteralPath $LogPath -Value $entry -Encoding utf8
    }
    catch {
        Write-Warning "Log entry could not be written: $($_.Exception.Message)"
    }
}

function Invoke-Main {
    [CmdletBinding()]
    param()

    Write-Log -Message "Starting script for target '$Target'."

    # -----------------------------------------------------------------
    # PRE-CHECKS
    # Add validation here before any changes are made.
    # -----------------------------------------------------------------

    Write-Verbose "Target: $Target"
    Write-Verbose "LogPath: $LogPath"
    Write-Verbose "Force: $Force"

    # -----------------------------------------------------------------
    # MODIFYING OPERATION EXAMPLE
    # All commands that change a system should be protected by
    # ShouldProcess whenever technically possible.
    # -----------------------------------------------------------------

    if ($PSCmdlet.ShouldProcess($Target, '<Describe the change here>')) {
        # Place the modifying command here.
        # Example:
        # Set-Something -Target $Target

        Write-Log -Message "Change completed for '$Target'." -Level 'OK'
    }
    else {
        Write-Log -Message "Change skipped for '$Target'." -Level 'INFO'
    }
}

try {
    Write-Log -Message 'Script started.'
    Invoke-Main
    Write-Log -Message 'Script completed successfully.' -Level 'OK'
}
catch {
    $errorMessage = $_.Exception.Message

    try {
        Write-Log -Message $errorMessage -Level 'ERROR'
    }
    catch {
        Write-Warning "The original error was: $errorMessage"
    }

    throw
}
finally {
    Write-Verbose 'Script execution finished.'
}
